<a href="https://colab.research.google.com/github/swarna32/EmotionClassificationTFIDF-RandomForest/blob/main/EmotionClassificationTFIDF_RandomForest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
emotion_data = pd.read_csv('/content/drive/MyDrive/Dataset/Emotion_final.csv')

In [ ]:
emotion_data

Text  Emotion
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
21454               Melissa stared at her friend in dism     fear
21455  Successive state elections have seen the gover...     fear
21456               Vincent was irritated but not dismay     fear
21457  Kendall-Hume turned back to face the dismayed ...     fear
21458                    I am dismayed , but not surpris     fear

[21459 rows x 2 columns]

In [ ]:
y = emotion_data['Emotion']

In [ ]:
y

0        sadness
1        sadness
2          anger
3           love
4          anger
          ...   
21454       fear
21455       fear
21456       fear
21457       fear
21458       fear
Name: Emotion, Length: 21459, dtype: object

In [ ]:
emotion_data.Emotion.unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'happy'],
      dtype=object)

In [ ]:
y = y.to_numpy().astype('str')

In [ ]:
y

array(['sadness', 'sadness', 'anger', ..., 'fear', 'fear', 'fear'],
      dtype='<U8')

In [ ]:
emotion_body = emotion_data.iloc[:,1]

In [ ]:
emotion_body

0        sadness
1        sadness
2          anger
3           love
4          anger
          ...   
21454       fear
21455       fear
21456       fear
21457       fear
21458       fear
Name: Emotion, Length: 21459, dtype: object

In [ ]:
emotion_body = emotion_data['Text']

In [ ]:
t=emotion_body.to_numpy()

In [ ]:
t

array(['i didnt feel humiliated',
       'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake',
       'im grabbing a minute to post i feel greedy wrong', ...,
       'Vincent was irritated but not dismay',
       'Kendall-Hume turned back to face the dismayed coup',
       'I am dismayed , but not surpris'], dtype=object)

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
import nltk
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


True

In [ ]:
from nltk.stem import WordNetLemmatizer
import re
documents = []
stemmer = WordNetLemmatizer()
for sen in range(0, len(t)):
    # Remove all the special characters
    document = re.sub(r'\W', ' ', str(t[sen]))
    # remove all single characters from middle
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)
    # Remove single characters from the start
    document = re.sub(r'\^[a-zA-Z]\s+', ' ', document)
    # Substituting multiple spaces with single space
    document = re.sub(r'\s+', ' ', document, flags=re.I)
    # Converting to Lowercase
    document = document.lower()
    document = re.sub("^\d+\s|\s\d+\s|\s\d+$", ' ', document)
    # Lemmatization
    document = document.split()
    document = [stemmer.lemmatize(word) for word in document]
    document = ' '.join(document)
    documents.append(document)

In [ ]:
documents

['i didnt feel humiliated',
 'i can go from feeling so hopeless to so damned hopeful just from being around someone who care and is awake',
 'im grabbing minute to post feel greedy wrong',
 'i am ever feeling nostalgic about the fireplace will know that it is still on the property',
 'i am feeling grouchy',
 'ive been feeling little burdened lately wasnt sure why that wa',
 'ive been taking or milligram or time recommended amount and ive fallen asleep lot faster but also feel like so funny',
 'i feel a confused about life a teenager or a jaded a year old man',
 'i have been with petronas for year feel that petronas ha performed well and made huge profit',
 'i feel romantic too',
 'i feel like have to make the suffering m seeing mean something',
 'i do feel that running is divine experience and that can expect to have some type of spiritual encounter',
 'i think it the easiest time of year to feel dissatisfied',
 'i feel low energy m just thirsty',
 'i have immense sympathy with the gen

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
vectorizer = TfidfVectorizer( encoding='utf-8',stop_words=stopwords.words('english'))
X = vectorizer.fit_transform(documents).toarray()
terms = vectorizer.get_feature_names()
print(len(terms))

17019


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
X.shape

(21459, 17019)

In [ ]:
terms

['000',
 '1980s',
 '19th',
 '20th',
 '23',
 '23r',
 '40th',
 '75th',
 '82nd',
 '94',
 '95',
 '9th',
 'aa',
 'aaaaaaand',
 'aaaaand',
 'aaaah',
 'aaaand',
 'aac',
 'aahhh',
 'aaron',
 'ab',
 'abandon',
 'abandoned',
 'abandoning',
 'abandonment',
 'abated',
 'abba',
 'abbigail',
 'abc',
 'abd',
 'abdomen',
 'abdominal',
 'abducted',
 'abelard',
 'abhorrent',
 'abide',
 'abigail',
 'ability',
 'abit',
 'abjectly',
 'able',
 'ableness',
 'ablo',
 'abnormally',
 'aboard',
 'abolitionist',
 'abominable',
 'abortion',
 'abou',
 'abound',
 'abraham',
 'abroad',
 'abruptly',
 'absence',
 'absoloutely',
 'absolute',
 'absolutely',
 'absolutly',
 'absorbed',
 'absorption',
 'abstain',
 'abstinence',
 'abstract',
 'absurd',
 'absurdity',
 'absurdly',
 'abt',
 'abu',
 'abundance',
 'abundantly',
 'abus',
 'abuse',
 'abused',
 'abusing',
 'abusive',
 'abyss',
 'ac',
 'academia',
 'academic',
 'academy',
 'acause',
 'accelerated',
 'accent',
 'accentuating',
 'accept',
 'acceptable',
 'acceptance',


In [ ]:
print(terms[5])

23r


In [ ]:
 Y=[]
 for i in range(len(y)):
     if y[i] =='anger':
       Y.append(0)
     elif y[i] == 'fear':
       Y.append(1)
     elif y[i] == 'happy':
       Y.append(2)
     elif y[i] == 'love':
       Y.append(3)
     elif y[i] == 'sadness':
       Y.append(4)
     elif y[i] == 'surprise':
       Y.append(5)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[225  83  88  57 109  38]
 [ 48 200  80  40  99  59]
 [158 154 485 246 204 152]
 [ 18  33  63 120  63  28]
 [170 294 145 136 399 114]
 [ 13  27  33  15  36  60]]
              precision    recall  f1-score   support

       anger       0.36      0.38      0.37       600
        fear       0.25      0.38      0.30       526
       happy       0.54      0.35      0.42      1399
        love       0.20      0.37      0.26       325
     sadness       0.44      0.32      0.37      1258
    surprise       0.13      0.33      0.19       184

    accuracy                           0.35      4292
   macro avg       0.32      0.35      0.32      4292
weighted avg       0.41      0.35      0.36      4292

0.34692451071761415


In [ ]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier(random_state=0)
DT.fit(X_train, y_train)
y_pred = DT.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))


[[ 528   18   10    2   41    1]
 [  25  451   10    2   22   16]
 [  29   17 1237   63   45    8]
 [   2    3   71  242    5    2]
 [  46   36   40    7 1119   10]
 [   5   23   15    1    8  132]]
              precision    recall  f1-score   support

       anger       0.83      0.88      0.86       600
        fear       0.82      0.86      0.84       526
       happy       0.89      0.88      0.89      1399
        love       0.76      0.74      0.75       325
     sadness       0.90      0.89      0.90      1258
    surprise       0.78      0.72      0.75       184

    accuracy                           0.86      4292
   macro avg       0.83      0.83      0.83      4292
weighted avg       0.86      0.86      0.86      4292

0.864165890027959


In [ ]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state=0).fit(X, y)
LR.fit(X_train, y_train)
y_pred = LR.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


[[ 489   12   45    1   53    0]
 [  25  406   46    2   39    8]
 [   6    5 1332   21   34    1]
 [   2    3   94  208   18    0]
 [  21   16   46    2 1172    1]
 [   4   27   42    0   19   92]]
              precision    recall  f1-score   support

       anger       0.89      0.81      0.85       600
        fear       0.87      0.77      0.82       526
       happy       0.83      0.95      0.89      1399
        love       0.89      0.64      0.74       325
     sadness       0.88      0.93      0.90      1258
    surprise       0.90      0.50      0.64       184

    accuracy                           0.86      4292
   macro avg       0.88      0.77      0.81      4292
weighted avg       0.86      0.86      0.86      4292

0.8618359739049394


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors=3)
KNN.fit(X_train, y_train)
y_pred = KNN.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[554   4  16   4  22   0]
 [232 243  14   3  24  10]
 [489  11 841  17  39   2]
 [163   2  28 124   8   0]
 [411  13  29   1 802   2]
 [111  10  17   0   6  40]]
              precision    recall  f1-score   support

       anger       0.28      0.92      0.43       600
        fear       0.86      0.46      0.60       526
       happy       0.89      0.60      0.72      1399
        love       0.83      0.38      0.52       325
     sadness       0.89      0.64      0.74      1258
    surprise       0.74      0.22      0.34       184

    accuracy                           0.61      4292
   macro avg       0.75      0.54      0.56      4292
weighted avg       0.79      0.61      0.64      4292

0.6067101584342963
